export interface ResponseData {
	SALVAGE_VALUE: number;
	BOOK_VALUE: number;
	ACCUMULATED_DEPRECIATION: number;
	OUTPUT_DEPRECIATION_RATE_IN_EXPECTED: number;
	OUTPUT_DEPRECIATION_RATE_IN_MILEAGE: number;
}
